#!/usr/bin/env node
/**
 * ledger-split.mjs — turn 06-knowledge-ledger.md back into an INDEX.
 *
 * The ledger's own stated rule is: "does NOT copy content, only one line per
 * lesson + a pointer". Over ~200 entries that rule eroded — individual rows
 * grew to 2500+ characters, and the file reached 421KB (~105K tokens). At that
 * size the archival tier is no longer readable in one pass, which defeats the
 * point of having an index at all.
 *
 * This script restores the invariant mechanically:
 *   - Section A rows move, in full and unedited, into nuc-platform/ledger/YYYY-MM.md
 *   - Section A becomes a short index: date + headline + a link to the detail
 *   - Section B (project pointers) is already thin and is carried over verbatim
 *
 * No lesson text is summarised, rewritten, or dropped — only relocated. The
 * headline shown in the index is extracted deterministically (the entry's own
 * leading **bold** span), never generated by a model.
 *
 * Usage
 *   node .claude/scripts/ledger-split.mjs --dry-run   # report only (default)
 *   node .claude/scripts/ledger-split.mjs --apply     # write the files
 */

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const REPO = resolve(".");
const LEDGER = join(REPO, "nuc-platform", "06-knowledge-ledger.md");
const OUT_DIR = join(REPO, "nuc-platform", "ledger");
const APPLY = process.argv.includes("--apply");

const HEADING_A = "## A. Cross-project lessons (content here)";
const HEADING_B = "## B. Pointers to each project's knowledge log";
/** Index rows stay scannable; longer headlines are cut at a word boundary. */
const HEADLINE_MAX = 120;

// ------------------------------------------------------------------ guards --

if (!existsSync(LEDGER)) {
  console.error(`ledger not found: ${LEDGER}`);
  process.exit(1);
}

if (APPLY) {
  // Never overwrite work the user (or a parallel session) has in flight.
  try {
    const dirty = execFileSync("git", ["status", "--porcelain", "--", LEDGER], {
      cwd: REPO,
      encoding: "utf8",
    }).trim();
    if (dirty) {
      console.error(`refusing to rewrite: ${LEDGER} has uncommitted changes`);
      console.error(`  ${dirty}`);
      console.error("commit or stash them first, then re-run.");
      process.exit(1);
    }
  } catch {
    console.error("could not read git status — refusing to rewrite unverified state.");
    process.exit(1);
  }
}

// ------------------------------------------------------------------- parse --

const src = readFileSync(LEDGER, "utf8");
const lines = src.split(/\r?\n/);

const idxA = lines.findIndex((l) => l.trim() === HEADING_A);
const idxB = lines.findIndex((l) => l.trim() === HEADING_B);
if (idxA === -1 || idxB === -1 || idxB < idxA) {
  console.error("could not locate section A / section B headings — aborting.");
  process.exit(1);
}

const preamble = lines.slice(0, idxA);
const sectionA = lines.slice(idxA, idxB);
const sectionB = lines.slice(idxB);

const ROW = /^\|\s*(\d{4}-\d{2}-\d{2})\s*\|\s*(.*?)\s*\|?\s*$/;

const entries = [];
const unparsed = [];
for (const line of sectionA) {
  if (!line.startsWith("|")) continue;
  const m = line.match(ROW);
  if (!m) {
    // Header and separator rows are expected; anything else is a real miss.
    if (!/^\|\s*(Date|-+)\s*\|/.test(line)) unparsed.push(line.slice(0, 90));
    continue;
  }
  entries.push({ date: m[1], body: m[2].replace(/\s*\|\s*$/, "").trim() });
}

if (unparsed.length) {
  console.error(`${unparsed.length} row(s) in section A did not parse — aborting to avoid data loss:`);
  for (const u of unparsed) console.error(`  ${u}`);
  process.exit(1);
}

// -------------------------------------------------------------- transform ---

/** The entry's own leading bold span is its headline. No model involved. */
function headline(body) {
  const bold = body.match(/\*\*(.+?)\*\*/);
  let text = bold ? bold[1] : body.split(/(?<=[.!?])\s/)[0] || body;
  text = text
    .replace(/`([^`]*)`/g, "$1")
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/[*_]/g, "")
    .replace(/\s+/g, " ")
    .trim();
  if (text.length <= HEADLINE_MAX) return text;
  const cut = text.slice(0, HEADLINE_MAX);
  return `${cut.slice(0, cut.lastIndexOf(" ") > 40 ? cut.lastIndexOf(" ") : HEADLINE_MAX)}…`;
}

const slugSeen = new Map();
function slug(date, text) {
  const base = `${date}-${text}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 70)
    .replace(/-$/, "");
  const n = (slugSeen.get(base) ?? 0) + 1;
  slugSeen.set(base, n);
  return n === 1 ? base : `${base}-${n}`;
}

const byMonth = new Map();
for (const e of entries) {
  e.headline = headline(e.body);
  e.slug = slug(e.date, e.headline);
  const month = e.date.slice(0, 7);
  if (!byMonth.has(month)) byMonth.set(month, []);
  byMonth.get(month).push(e);
}

const months = [...byMonth.keys()].sort();

// ----------------------------------------------------------------- render ---

function renderMonth(month, list) {
  const out = [
    `# Knowledge ledger — ${month}`,
    "",
    "> Full text of the cross-project lessons recorded this month. The scannable index",
    "> lives in `../06-knowledge-ledger.md`; this file holds the detail it points at.",
    "> **Append-only** — a superseded lesson gets a later entry that links back, it is not edited away.",
    "",
    `${list.length} entries.`,
    "",
    "---",
    "",
  ];
  for (const e of list) {
    out.push(`### ${e.date} — ${e.headline}`, "", `<a id="${e.slug}"></a>`, "", e.body, "");
  }
  return `${out.join("\n").trimEnd()}\n`;
}

function renderIndex() {
  const out = [
    ...preamble,
    HEADING_A,
    "",
    `> **Index only.** ${entries.length} lessons, full text in \`ledger/YYYY-MM.md\`. One row = one lesson:`,
    "> the headline plus a link. **Do not paste detail back into this table** — that is exactly how this",
    "> file grew to 421KB and stopped being readable. New lesson → append the full text to the current",
    "> month's file, then add one row here.",
    "",
    "| Date | Lesson | Detail |",
    "| ---------- | --- | --- |",
  ];
  for (const e of entries) {
    const month = e.date.slice(0, 7);
    const safe = e.headline.replace(/\|/g, "\\|");
    out.push(`| ${e.date} | ${safe} | [→](ledger/${month}.md#${e.slug}) |`);
  }
  out.push("", ...sectionB);
  return `${out.join("\n").trimEnd()}\n`;
}

// ------------------------------------------------------------------- main ---

const newIndex = renderIndex();
const monthFiles = months.map((m) => ({
  month: m,
  path: join(OUT_DIR, `${m}.md`),
  content: renderMonth(m, byMonth.get(m)),
}));

const before = Buffer.byteLength(src);
const afterIndex = Buffer.byteLength(newIndex);
const afterDetail = monthFiles.reduce((n, f) => n + Buffer.byteLength(f.content), 0);

const kb = (n) => `${(n / 1024).toFixed(1)}KB`;
const tok = (n) => `~${Math.round(n / 4 / 1000)}K tok`;

console.log(`entries parsed:      ${entries.length}`);
console.log(`months:              ${months.join(", ")}`);
console.log(`index  before/after: ${kb(before)} (${tok(before)})  ->  ${kb(afterIndex)} (${tok(afterIndex)})`);
console.log(`detail files:        ${kb(afterDetail)} across ${monthFiles.length} file(s)`);
console.log(
  `content preserved:   ${afterIndex + afterDetail >= before * 0.95 ? "yes" : "CHECK"} ` +
    `(${kb(afterIndex + afterDetail)} total vs ${kb(before)} original)`,
);

if (!APPLY) {
  console.log("\nDRY RUN — nothing written. Re-run with --apply to write.");
  console.log("first 3 index rows:");
  for (const l of newIndex.split("\n").filter((l) => l.startsWith("| 2026")).slice(0, 3)) {
    console.log(`  ${l.slice(0, 150)}`);
  }
  process.exit(0);
}

mkdirSync(OUT_DIR, { recursive: true });
for (const f of monthFiles) writeFileSync(f.path, f.content, "utf8");
writeFileSync(LEDGER, newIndex, "utf8");
console.log(`\nwrote ${monthFiles.length} month file(s) + rewrote the index.`);
console.log("review with: git diff --stat && git status");
